"""empty message

Revision ID: 0b2c21919196
Revises: a66154551af4
Create Date: 2020-07-01 18:33:59.851947

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from app import PidController, db

revision = '0b2c21919196'
down_revision = 'a66154551af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pid_controller', sa.Column('unit', sa.Enum('F', 'C', 'PPM', 'percent', ''), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pid_controller', 'unit')
    # ### end Alembic commands ###
