"""empty message

Revision ID: 5196af012cb0
Revises: 0b2c21919196
Create Date: 2020-07-01 19:10:14.653962

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
from app import PidController, db

revision = '5196af012cb0'
down_revision = '0b2c21919196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pid_controller', sa.Column('reading', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.add_column('pid_controller', sa.Column('set_point', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
    db.session.add(PidController("TIC_101", unit='C'))
    db.session.add(PidController("HIC_101", unit='percent'))
    db.session.add(PidController("GIC_101", unit='PPM'))
    db.session.commit()
    tic_101 = PidController.query.filter_by(name="TIC_101").first()
    hic_101 = PidController.query.filter_by(name="HIC_101").first()
    gic_101 = PidController.query.filter_by(name="GIC_101").first()
    tic_101.reading = 25.6
    tic_101.set_point = 35.2
    gic_101.reading = 13500
    gic_101.set_point = 15000
    hic_101.reading = 0.46
    hic_101.set_point = 0.80
    db.session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pid_controller', 'set_point')
    op.drop_column('pid_controller', 'reading')
    # ### end Alembic commands ###
