"""empty message

Revision ID: a66154551af4
Revises: 
Create Date: 2020-06-30 21:06:20.366572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from app import PidController, db

revision = 'a66154551af4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pid_controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=True),
    sa.Column('P', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('I', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('D', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('mode', sa.Enum('Manual', 'Auto', 'Master'), nullable=True),
    sa.Column('output_port', sa.String(length=150), nullable=True),
    sa.Column('input_port', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    db.session.add(PidController("TIC_101"))
    db.session.add(PidController("HIC_101"))
    db.session.add(PidController("GIC_101"))
    db.session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reading')
    op.drop_table('pid_controller')
    op.drop_table('output')
    # ### end Alembic commands ###
